version: '3.3'
services:
  restesque:
    build: .
    restart: unless-stopped
    depends_on: 
    - restesque-redis
    ports:
    - "6969:6969"
    environment:
    - REDIS_PORT=6379
    - REDIS_HOST=restesque-redis
  restesque-redis:
    image: redis
    restart: unless-stopped
